'use strict'

/** Generated by Serverless About Plugin at #{creationDate} */
const functionObjects = JSON.parse('#{components}')
module.exports.about = (event, context, callback) => {
  let componentResponses = []
  functionObjects.forEach((functionObject) => {
    functionObject.about.forEach((about) => {
      const componentBody = about.info
      componentBody.lastUpdated = new Date().toISOString()
      componentResponses.push(componentBody)
    })
  })
  const aboutBody = JSON.parse('#{outputHeader}')
  aboutBody.components = componentResponses
  callback(null, {
    statusCode: 200,
    body: JSON.stringify(aboutBody),
    headers: {
      'Content-Type': 'application/json'
    }
  })
}
